from src.classes.action import Action

ACTION_NAME = str
ACTION_PARAMS = dict
ACTION_PAIR = tuple[Action, ACTION_PARAMS]
ACTION_NAME_PARAMS_PAIR = tuple[ACTION_NAME, ACTION_PARAMS]
ACTION_NAME_PARAMS_PAIRS = list[ACTION_NAME_PARAMS_PAIR]